export const APP_API_URL = 'https://api-demo.entraos.io';
export const APP_ENVIRONMENT_NAME = 'demo';
export const APP_GIT_SHA = 'sha';
//export const APP_BASE_URL = 'https://api-demo.entraos.io';
export const APP_BASE_URL = 'https://api-demo.entraos.io';
export const OAUTH_CLIENT_ID = 'aN6hrfyLwBl3PTnWKWWn_g--';
export const OAUTH_DOMAIN= 'entrasso-demo.entraos.io/oauth2'
export const OAUTH_REDIRECT_URI = `${APP_BASE_URL}`
export const OAUTH_SCOPE = 'openid profile phone email'
export const OAUTH_AUTO_RENEW_TOKEN = true
export const LOCALSTORAGE_ACCESS_TOKEN = 'ACCESS_TOKEN'
export const LOCALSTORAGE_REFRESH_TOKEN = 'REFRESH_TOKEN'
export const LOCALSTORAGE_ID_TOKEN = 'USERINFO_TOKEN'
